spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1/carryit-vehicle
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

graphiql:
  enabled: true
  static:
    basepath: /
  cdn:
    enabled: false