spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1/carryit
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

graphiql:
  enabled: true
  static:
    basepath: /
  cdn:
    enabled: false